# Generated by Django 3.2 on 2021-04-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='email',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
